packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  esbuild: true
  msgpackr-extract: true
  prisma: true
minimumReleaseAgeExclude:
  - "@turbo/darwin-64@2.11.1"
  - "@turbo/darwin-arm64@2.11.1"
  - "@turbo/linux-64@2.11.1"
  - "@turbo/linux-arm64@2.11.1"
  - "@turbo/windows-64@2.11.1"
  - "@turbo/windows-arm64@2.11.1"
  - prettier@3.9.8
  - turbo@2.11.1
  - "@yuva-devlab/tokens@1.0.0"
  - "@yuva-devlab/tokens@1.1.0"
  - "@yuva-devlab/ui@1.0.1"
  - "@yuva-devlab/ui@1.1.0"
  - "@yuva-devlab/ui@1.2.0"
  - "@yuva-devlab/ui@1.3.0"
  - "@yuva-devlab/logger@1.1.0"
overrides:
  rollup-plugin-dts: "^6.5.1"
