/**
 * @file packages/core/src/messages/content-block.schema.ts
 * @description Multimodal and structured content blocks within messages.
 */

import { z } from "zod";
import { ToolCallIdSchema } from "@/identifiers";

/**
 * Standard plain-text content block.
 */
export const TextContentBlockSchema = z.object({
  type: z.literal("text"),
  text: z.string().describe("Textual string content"),
});

export type TextContentBlock = z.infer<typeof TextContentBlockSchema>;

/**
 * Visual or media asset content block.
 */
export const ImageContentBlockSchema = z.object({
  type: z.literal("image"),
  mediaType: z.string().default("image/png").describe("MIME type of the media (e.g. image/jpeg)"),
  data: z.string().describe("Base64 encoded payload or public URL"),
});

export type ImageContentBlock = z.infer<typeof ImageContentBlockSchema>;

/**
 * Explicit model reasoning/thought block (used by DeepSeek-R1, Claude thinking, OpenAI reasoning).
 */
export const ThoughtContentBlockSchema = z.object({
  type: z.literal("thought"),
  thought: z.string().describe("Internal model reasoning or chain-of-thought text"),
});

export type ThoughtContentBlock = z.infer<typeof ThoughtContentBlockSchema>;

/**
 * Tool call invocation block generated by the model.
 */
export const ToolCallContentBlockSchema = z.object({
  type: z.literal("tool_call"),
  callId: ToolCallIdSchema,
  toolName: z.string().min(1).describe("Target tool name"),
  arguments: z.record(z.string(), z.unknown()).describe("Parsed arguments provided to the tool"),
});

export type ToolCallContentBlock = z.infer<typeof ToolCallContentBlockSchema>;

/**
 * Tool execution result block returned to the model.
 */
export const ToolResultContentBlockSchema = z.object({
  type: z.literal("tool_result"),
  callId: ToolCallIdSchema,
  isError: z.boolean().default(false).describe("Whether the tool execution failed"),
  output: z.unknown().describe("Result value returned by the tool"),
});

export type ToolResultContentBlock = z.infer<typeof ToolResultContentBlockSchema>;

/**
 * Discriminated union of all supported message content blocks.
 */
export const ContentBlockSchema = z.discriminatedUnion("type", [
  TextContentBlockSchema,
  ImageContentBlockSchema,
  ThoughtContentBlockSchema,
  ToolCallContentBlockSchema,
  ToolResultContentBlockSchema,
]);

export type ContentBlock = z.infer<typeof ContentBlockSchema>;
