/**
 * @file packages/runtime/src/checkpoint/retention/checkpoint-pruner.ts
 * @description Pruning engine that compacts execution checkpoint histories while preserving critical milestones.
 */

import type { CheckpointRecord } from "../checkpoint.types";
import type { IPersistentCheckpointer } from "../database-adapter.interface";
import {
  type CheckpointRetentionPolicy,
  CheckpointRetentionPolicySchema,
} from "./retention-policy";

/**
 * Sweeper engine that prunes redundant intermediate checkpoints to enforce database retention bounds.
 */
export class CheckpointPruner<TState = unknown> {
  private readonly checkpointer: IPersistentCheckpointer<TState>;
  private readonly policy: CheckpointRetentionPolicy;

  public constructor(
    checkpointer: IPersistentCheckpointer<TState>,
    policy: Partial<CheckpointRetentionPolicy> = {},
  ) {
    this.checkpointer = checkpointer;
    this.policy = CheckpointRetentionPolicySchema.parse(policy);
  }

  /**
   * Evaluates an execution's checkpoint list and determines which step indices should be retained.
   *
   * @param checkpoints - Ordered array of historical checkpoints.
   * @returns Array of step indices to retain.
   */
  public evaluateRetainedIndices(checkpoints: readonly CheckpointRecord<TState>[]): number[] {
    // Guard: If total snapshots are within policy limit, retain all
    if (checkpoints.length <= this.policy.maxCheckpointsPerRun) {
      return checkpoints.map((c) => c.stepIndex);
    }

    const retainedIndices = new Set<number>();
    const milestoneSet = new Set(this.policy.milestoneNodes);

    // 1. Invariant: Always retain the initial snapshot and the latest terminal snapshot
    if (checkpoints[0]) {
      retainedIndices.add(checkpoints[0].stepIndex);
    }
    const lastCheckpoint = checkpoints[checkpoints.length - 1];
    if (lastCheckpoint) {
      retainedIndices.add(lastCheckpoint.stepIndex);
    }

    // 2. Identify milestone nodes if configured
    if (this.policy.preserveMilestones) {
      for (const cp of checkpoints) {
        // Retain checkpoints generated by milestone nodes (e.g. tool execution or approval gates)
        if (milestoneSet.has(cp.nodeName)) {
          retainedIndices.add(cp.stepIndex);
        }
      }
    }

    // 3. Keep recent intermediate steps to fill up to maxCheckpointsPerRun limit
    const remainingSlots = this.policy.maxCheckpointsPerRun - retainedIndices.size;
    if (remainingSlots > 0) {
      // Pick most recent non-retained checkpoints backwards
      for (
        let i = checkpoints.length - 1;
        i >= 0 && retainedIndices.size < this.policy.maxCheckpointsPerRun;
        i--
      ) {
        const cp = checkpoints[i];
        if (cp) {
          retainedIndices.add(cp.stepIndex);
        }
      }
    }

    return Array.from(retainedIndices).sort((a, b) => a - b);
  }

  /**
   * Executes a pruning sweep for an execution, deleting non-retained checkpoints from storage.
   *
   * @param executionId - Execution run identifier.
   * @returns Number of checkpoints pruned.
   */
  public async pruneExecution(executionId: string): Promise<number> {
    const list = await this.checkpointer.list(executionId);

    // Guard: Skip pruning if count is already within policy limit
    if (list.length <= this.policy.maxCheckpointsPerRun) {
      return 0;
    }

    const retainedIndices = this.evaluateRetainedIndices(list);
    return this.checkpointer.prune(executionId, retainedIndices);
  }
}
