/**
 * @file packages/models/src/interfaces/llm-adapter.interface.ts
 * @description Core provider-agnostic LLM adapter contract for OrchestrAI.
 *
 * ─── Why a unified interface? (Learning note) ───────────────────────────────
 * Every AI provider (Ollama, OpenAI, Anthropic) has a completely different API
 * surface. Without an abstraction, your agent code becomes a mess of `if (provider
 * === 'openai')` branches. By defining ILlmAdapter, the entire agent layer only
 * ever sees ONE interface — regardless of whether it's talking to a local Ollama
 * model or GPT-4o. This is the Adapter design pattern applied to AI engineering.
 * ────────────────────────────────────────────────────────────────────────────
 */

import { z } from "zod";
import type { ModelProvider } from "@orchestrai/core";
import { AIMessageSchema, ModelUsageSchema, AGENT_EXECUTION_DEFAULTS } from "@orchestrai/core";

// ─── Request Schema ─────────────────────────────────────────────────────────

/**
 * Canonical request payload sent to any LLM adapter.
 *
 * Design note: We use `messages` (the conversation history array) rather than
 * a single `prompt` string because every modern LLM API — Ollama, OpenAI,
 * Anthropic — uses a message-list format. This maps 1:1 to what they all expect.
 *
 * @example
 * const req: LlmRequest = {
 *   model: "qwen2.5:7b",
 *   messages: [
 *     { role: "user", content: [{ type: "text", text: "Hello!" }] }
 *   ],
 *   temperature: 0.7,
 *   maxTokens: 1024,
 * };
 */
export const LlmRequestSchema = z.object({
  /** Provider-specific model identifier string */
  model: z.string().min(1).optional().describe("Provider model name"),

  /** Ordered conversation history including system, user, and assistant turns */
  messages: z.array(AIMessageSchema).min(1).describe("Ordered message history sent to the model"),

  /** Sampling temperature: 0.0 = deterministic, 1.0 = creative (default: AGENT_EXECUTION_DEFAULTS.DEFAULT_TEMPERATURE) */
  temperature: z
    .number()
    .min(0)
    .max(2)
    .default(AGENT_EXECUTION_DEFAULTS.DEFAULT_TEMPERATURE)
    .describe("Sampling temperature"),

  /** Hard cap on generated output tokens to prevent runaway completions */
  maxTokens: z.number().int().positive().optional().describe("Maximum output tokens"),

  /** When true, the adapter must return an AsyncIterable instead of a full response */
  stream: z.boolean().default(false).describe("Enable token streaming"),
});

/** Inferred TypeScript type for LlmRequest */
export type LlmRequest = z.infer<typeof LlmRequestSchema>;

// ─── Response Schema ─────────────────────────────────────────────────────────

/**
 * Standardized non-streaming response from any LLM adapter.
 *
 * Design note: `content` is always a plain string here (the concatenated text).
 * Structured outputs (JSON mode, tool calls) are higher-level features
 * handled by the agent layer on top of this primitive.
 */
export const LlmResponseSchema = z.object({
  /** The raw text generated by the model */
  content: z.string().describe("Generated text content"),

  /** Token consumption statistics from this invocation */
  usage: ModelUsageSchema.optional().describe("Token usage metrics"),

  /** Provider's finish reason (e.g. "stop", "length", "tool_calls") */
  finishReason: z.string().optional().describe("Why the model stopped generating"),
});

/** Inferred TypeScript type for LlmResponse */
export type LlmResponse = z.infer<typeof LlmResponseSchema>;

// ─── Stream Chunk Schema ──────────────────────────────────────────────────────

/**
 * A single delta chunk emitted during a streaming invocation.
 *
 * Learning note — Streaming in LLMs:
 * When you call an LLM with streaming=true, the model doesn't wait until the
 * entire answer is ready. Instead it sends tokens one-by-one as they're generated.
 * Each tiny piece is a "chunk" or "delta". The UI renders them in real time —
 * that's how ChatGPT's typing effect works. `delta` is the new text in this chunk;
 * your code concatenates all deltas to build the final response.
 */
export const LlmStreamChunkSchema = z.object({
  /** Incremental text generated in this chunk (may be empty for final chunk) */
  delta: z.string().describe("Incremental token delta"),

  /** Whether this is the final chunk in the stream */
  done: z.boolean().default(false).describe("True on the terminal chunk"),

  /** Usage statistics — only populated on the final chunk (done=true) */
  usage: ModelUsageSchema.optional().describe("Token usage, final chunk only"),
});

/** Inferred TypeScript type for LlmStreamChunk */
export type LlmStreamChunk = z.infer<typeof LlmStreamChunkSchema>;

// ─── Adapter Interface ────────────────────────────────────────────────────────

/**
 * The unified LLM adapter contract all provider implementations must satisfy.
 *
 * Implementors:
 *  - OllamaAdapter   → talks to local Ollama server
 *  - OpenAiAdapter   → talks to OpenAI API (or compatible endpoints)
 *  - AnthropicAdapter → talks to Anthropic Claude API
 *
 * Learning note — AsyncIterable<T>:
 * `stream()` returns `AsyncIterable<LlmStreamChunk>`. You consume it like:
 *   ```ts
 *   for await (const chunk of adapter.stream(request)) {
 *     process.stdout.write(chunk.delta); // print token-by-token
 *   }
 *   ```
 * This is the idiomatic Node.js pattern for streaming data — no callbacks,
 * no EventEmitters. Just a clean async loop.
 */
export interface ILlmAdapter {
  /** The provider this adapter connects to (used by the registry and factory) */
  readonly provider: ModelProvider;

  /**
   * Invokes the model and returns the complete response after generation finishes.
   * Use this for non-interactive tasks where you don't need incremental output.
   *
   * @param request - Validated LlmRequest payload
   * @returns Promise resolving to the full generated response
   * @throws {ModelAdapterError} If the provider SDK is unavailable or the request fails
   */
  invoke(request: LlmRequest): Promise<LlmResponse>;

  /**
   * Streams the model response as an async iterable of token delta chunks.
   * Use this for chat UIs or realtime dashboards where you want immediate output.
   *
   * @param request - Validated LlmRequest payload (stream flag is ignored; always streams)
   * @returns AsyncIterable of LlmStreamChunk deltas
   * @throws {ModelAdapterError} If streaming is unsupported or the provider fails
   */
  stream(request: LlmRequest): AsyncIterable<LlmStreamChunk>;
}
