/**
 * @file packages/runtime/src/recovery/execution-recovery-manager.ts
 * @description Recovery coordinator analyzing interrupted runs, validating checksums, and building resume plans.
 */

import { OrchestrAIError } from "@orchestrai/core";
import { END } from "@/graph";
import type { IPersistentCheckpointer } from "@/checkpoint/database-adapter.interface";
import { verifyStateHash } from "@/checkpoint/serializer/state-hasher";
import type { RuntimeGraphState } from "@/nodes";
import type { InterruptedExecutionInfo, RecoveryPlan } from "./recovery-types";

/**
 * Coordinates crash detection, checksum validation, and graph state resumption for interrupted executions.
 */
export class ExecutionRecoveryManager {
  private readonly checkpointer: IPersistentCheckpointer<RuntimeGraphState>;

  public constructor(checkpointer: IPersistentCheckpointer<RuntimeGraphState>) {
    this.checkpointer = checkpointer;
  }

  /**
   * Evaluates the health and checkpoint state of an interrupted or stalled execution.
   *
   * @param executionId - Execution run identifier.
   * @returns Diagnostic InterruptedExecutionInfo.
   */
  public async inspectExecution(executionId: string): Promise<InterruptedExecutionInfo> {
    const latest = await this.checkpointer.loadLatest(executionId);
    if (!latest) {
      throw new OrchestrAIError(
        `Execution inspection failed: no checkpoints found for "${executionId}"`,
        "NOT_FOUND",
        404,
        { executionId },
      );
    }

    const state = latest.state;
    const isPausedAtApproval = Boolean(state.pendingApprovalId);
    // If stateHash is present, verify it; if omitted, consider valid
    const stateHashValid = latest.stateHash ? verifyStateHash(state, latest.stateHash) : true;

    return {
      executionId,
      lastStepIndex: latest.stepIndex,
      lastNodeName: latest.nodeName,
      lastActiveTimestamp: latest.timestamp,
      isPausedAtApproval,
      stateHashValid,
    };
  }

  /**
   * Generates a concrete recovery plan with target resumption node and validated state.
   *
   * @param executionId - Execution run identifier.
   * @returns Actionable RecoveryPlan.
   */
  public async planRecovery(executionId: string): Promise<RecoveryPlan> {
    const info = await this.inspectExecution(executionId);
    const latest = await this.checkpointer.loadLatest(executionId);
    if (!latest) {
      throw new OrchestrAIError(
        `Recovery planning failed: checkpoint vanished for "${executionId}"`,
        "NOT_FOUND",
        404,
        { executionId },
      );
    }

    // Branch 1: Corrupted state failed checksum verification
    if (!info.stateHashValid) {
      return {
        executionId,
        strategy: "FAIL_UNRECOVERABLE",
        targetResumeNode: END,
        reconstitutedState: latest.state,
        reason: "State integrity verification failed (tampered or corrupted checkpoint hash)",
      };
    }

    // Branch 2: Suspended at approval gate
    if (info.isPausedAtApproval) {
      return {
        executionId,
        strategy: "FAIL_UNRECOVERABLE",
        targetResumeNode: "approval_gate",
        reconstitutedState: latest.state,
        reason: "Execution is intentionally paused waiting for human operator approval",
      };
    }

    // Branch 3: Determine appropriate DAG node to resume from
    let targetNode = "model";
    let planReason = "Resuming execution loop from model node";

    if (info.lastNodeName === "model") {
      if (latest.state.pendingToolCalls && latest.state.pendingToolCalls.length > 0) {
        targetNode = "tool_evaluator";
        planReason = "Resuming to evaluate pending tool calls generated by model";
      } else {
        targetNode = END;
        planReason = "Execution had finished model reasoning without pending tool calls";
      }
    } else if (info.lastNodeName === "tool_evaluator") {
      targetNode = "tool_executor";
      planReason = "Resuming to execute validated tool calls";
    } else if (info.lastNodeName === "tool_executor") {
      targetNode = "model";
      planReason = "Tools executed; looping back to model node for synthesis";
    }

    return {
      executionId,
      strategy: "RESUME_IN_PLACE",
      targetResumeNode: targetNode,
      reconstitutedState: latest.state,
      reason: planReason,
    };
  }
}
