/**
 * @fileoverview Mock database execution runs and trace steps.
 * Adheres strictly to the 250-line maximum rule.
 */

import type { Execution } from "./types";

/**
 * Historical replayable execution sessions.
 */
export const executions: Execution[] = [
  {
    id: "EXE-8F29A",
    task: "Analyze this software architecture and research better alternatives.",
    agentId: "general",
    agent: "Supervisor",
    status: "running",
    mode: "delegated",
    duration: "14.2s",
    tools: 4,
    tokens: 3840,
    startedAt: "Today 12:41:02",
    completedAt: null,
    summary:
      "Supervisor decomposed intent into 3 parallel branches: literature, code boundary scan, and database schema audit.",
    steps: [
      {
        id: "s1",
        label: "Intent triage & plan DAG",
        agent: "Supervisor",
        type: "plan",
        duration: "1.2s",
        status: "done",
        input: "Review architecture proposals",
        output: "DAG built: 3 parallel tasks",
      },
      {
        id: "s2",
        label: "Inspect code boundaries",
        agent: "Developer Agent",
        type: "code",
        duration: "4.8s",
        status: "done",
        input: "Scan packages/* for leaky imports",
        output: "Zero boundary leaks found",
      },
      {
        id: "s3",
        label: "Retrieve prior research",
        agent: "Research Agent",
        type: "rag",
        duration: "3.1s",
        status: "done",
        input: "Query vector memory for outbox pattern",
        output: "Found 4 relevant documentation chunks",
      },
      {
        id: "s4",
        label: "Database read approval",
        agent: "Data Agent",
        type: "approval",
        duration: "5.1s",
        status: "waiting",
        input: "Inspect query metrics table",
        output: "Operator approval pending",
      },
    ],
    errors: [],
  },
  {
    id: "EXE-7C104",
    task: "Research PostgreSQL indexing strategies for high-write applications.",
    agentId: "research",
    agent: "Research Agent",
    status: "completed",
    mode: "autonomous",
    duration: "18.4s",
    tools: 4,
    tokens: 5240,
    startedAt: "Today 11:02:18",
    completedAt: "Today 11:02:43",
    summary:
      "Gathered 7 primary sources on B-tree vs BRIN indexing. Recommended partial index on status column.",
    steps: [
      {
        id: "s1",
        label: "Locate configuration files",
        agent: "Developer Agent",
        type: "file",
        duration: "1.1s",
        status: "done",
        input: "find . -name eslint.config.js",
        output: "Located 9 subpackage files",
      },
      {
        id: "s2",
        label: "Extract shared plugins",
        agent: "Developer Agent",
        type: "code",
        duration: "8.4s",
        status: "done",
        input: "Analyze typescript-eslint & tailwindcss rules",
        output: "Standardized rules mapped",
      },
      {
        id: "s3",
        label: "Run test lint suite",
        agent: "Developer Agent",
        type: "tool",
        duration: "15.1s",
        status: "done",
        input: "pnpm lint across packages",
        output: "Zero errors, zero warnings",
      },
    ],
    errors: [],
  },
  {
    id: "EXE-6B551",
    task: "Review my API architecture.",
    agentId: "developer",
    agent: "Developer Agent",
    status: "completed",
    mode: "supervised",
    duration: "8.2s",
    tools: 2,
    tokens: 1820,
    startedAt: "Yesterday 16:30:10",
    completedAt: "Yesterday 16:30:18",
    summary:
      "Traced dependency graph from REST handlers to data layer. Identified 2 N+1 query patterns.",
    steps: [
      {
        id: "s1",
        label: "Analyze query plan",
        agent: "Data Agent",
        type: "database",
        duration: "3.2s",
        status: "done",
        input: "EXPLAIN ANALYZE SELECT * FROM execution_events",
        output: "Sequential scan detected",
      },
      {
        id: "s2",
        label: "Apply index migration",
        agent: "Data Agent",
        type: "database",
        duration: "5.0s",
        status: "done",
        input: "CREATE INDEX idx_exec_created",
        output: "Index built successfully",
      },
    ],
    errors: [],
  },
  {
    id: "EXE-5A902",
    task: "Summarize last week's incident reports and extract recurring causes.",
    agentId: "data",
    agent: "Data Agent",
    status: "failed",
    mode: "supervised",
    duration: "18.2s",
    tools: 3,
    tokens: 4200,
    startedAt: "Yesterday 18:20:00",
    completedAt: "Yesterday 18:20:18",
    summary: "Operator rejected the aggregate query scope. Execution halted at approval gate.",
    steps: [
      {
        id: "s1",
        label: "Initial search crawl",
        agent: "Research Agent",
        type: "web",
        duration: "6.2s",
        status: "done",
        input: "search agent memory architectures",
        output: "28 URLs found",
      },
      {
        id: "s2",
        label: "Read documentation pages",
        agent: "Research Agent",
        type: "web",
        duration: "12.0s",
        status: "failed",
        input: "Fetch URL batch 1",
        output: "Rate limit 429 received",
      },
    ],
    errors: [
      { step: "s2", message: "HTTP 429 Too Many Requests from origin gateway", recovered: false },
    ],
  },
];
