/**
 * @file apps/console/src/lib/ui-copy/auth.ts
 * @description Centralized UI copy, placeholders, and error messages for Authentication screens.
 * @module apps/console/lib/ui-copy
 */

export const AUTH_COPY = {
  CARD: {
    HOME_A11Y: "OrchestrAI Home",
    BADGE_TEXT: "AI OPERATOR ACCESS",
    NODE_TELEMETRY: "ORCH-NODE-V1",
    ENGINE_STATUS: "ENGINE: READY",
    SWARM_ACTIVE: "MULTI-AGENT SWARM // ACTIVE",
    RUNTIME_READY: "AGENT RUNTIME // READY",
  },
  LOGOUT: {
    TOAST_SUCCESS: "Signed out successfully",
  },
  LOGIN: {
    PAGE_TITLE: "Sign In — OrchestrAI",
    PAGE_DESCRIPTION: "Sign in to access OrchestrAI Console.",
    CARD_TITLE: "Sign in to OrchestrAI",
    CARD_SUBTITLE: "Enter your email and password below",
    FOOTER_PROMPT: "Don't have an account?",
    FOOTER_LINK: "Sign up",
    EMAIL_LABEL: "Email",
    EMAIL_PLACEHOLDER: "name@example.com",
    PASSWORD_LABEL: "Password",
    PASSWORD_PLACEHOLDER: "••••••••",
    FORGOT_PASSWORD: "Forgot password?",
    SIGN_IN_BUTTON: "Sign In",
    SIGNING_IN: "Signing in...",
    TOAST_LOADING: "Authenticating operator...",
    TOAST_SUCCESS: "Authentication successful!",
    TOAST_ERROR: "Invalid email or password",
  },
  SIGNUP: {
    PAGE_TITLE: "Sign Up — OrchestrAI",
    PAGE_DESCRIPTION: "Create an account to access OrchestrAI Console.",
    CARD_TITLE: "Create an account",
    CARD_SUBTITLE: "Enter your email and password to get started",
    FOOTER_PROMPT: "Already have an account?",
    FOOTER_LINK: "Sign in",
    NAME_LABEL: "Your Name",
    NAME_PLACEHOLDER: "John Doe",
    EMAIL_LABEL: "Work Email",
    EMAIL_PLACEHOLDER: "john.doe@example.com",
    PASSWORD_LABEL: "Password",
    PASSWORD_PLACEHOLDER: "••••••••",
    CONFIRM_PASSWORD_LABEL: "Confirm Password",
    CONFIRM_PASSWORD_PLACEHOLDER: "••••••••",
    SIGN_UP_BUTTON: "Create Operator Account",
    SIGNING_UP: "Creating account...",
    TOAST_LOADING: "Provisioning operator tenancy...",
    TOAST_SUCCESS: "Account created successfully!",
    TOAST_ERROR: "Registration failed. Please try again.",
    NAME_REQUIRED: "Please enter your name",
    MISMATCH_ERROR: "Passwords do not match",
    PASSWORD_MIN_LENGTH: "Password must contain at least 6 characters",
  },
  FORGOT_PASSWORD: {
    PAGE_TITLE: "Reset Password — OrchestrAI",
    PAGE_DESCRIPTION: "Reset your OrchestrAI password.",
    CARD_TITLE: "Reset your password",
    CARD_SUBTITLE: "Enter your email to receive recovery instructions",
    FOOTER_PROMPT: "Remember your password?",
    FOOTER_LINK: "Sign in",
    EMAIL_LABEL: "Email",
    EMAIL_PLACEHOLDER: "name@example.com",
    SUBMIT_BUTTON: "Send Reset Instructions",
    SUBMITTING: "Sending instructions...",
    BACK_TO_LOGIN: "Back to sign in",
    TOAST_LOADING: "Dispatching recovery instructions...",
    TOAST_SUCCESS: "Recovery email dispatched successfully!",
    TOAST_ERROR: "Failed to send reset instructions. Please try again.",
  },
} as const;
