/**
 * @file apps/console/src/lib/ui-copy/executions.ts
 * @description Centralized UI copy, placeholders, and forensic trace text for Executions.
 * @module apps/console/lib/ui-copy
 */

export const EXECUTIONS_COPY = {
  PAGE_TITLE: "Executions",
  BREADCRUMB: "Executions",
  PAGE_DESCRIPTION: "Full audit log of autonomous execution runs and agent decisions.",
  SEARCH_PLACEHOLDER: "Search by ID, intent, or agent...",
  STATS: (count: number) => `${count} runs logged`,
  EMPTY_TITLE: "No Executions Logged",
  EMPTY_DESC: "Trigger an objective in Cowork Studio to generate your first audit trail.",
  NO_MATCH_TITLE: "No Executions Matched",
  NO_MATCH_DESC: (query: string) => `No execution traces matched your search query "${query}".`,
  DETAIL: {
    PAGE_TITLE: "Execution Trace",
    BREADCRUMB: "Trace Detail",
    NOT_FOUND_TITLE: "Execution Record Not Found",
    NOT_FOUND_DESC: (id: string) => `No recorded execution trace with ID "${id}" was found.`,
    METRICS_TITLE: "Telemetry & Spans",
    STEPS_TITLE: "Execution Steps",
    NO_STEPS_DESC: "No incremental loop steps recorded for this execution run.",
    INTENT_TITLE: "Execution Intent",
    TRACE_SUMMARY_TITLE: "Step Trace Summary",
    STEPS_LABEL: "Steps Completed",
    LATENCY_LABEL: "Latency",
    TOKENS_LABEL: "Tokens Billed",
    METADATA_TITLE: "Run Metadata",
    ID_LABEL: "Execution ID",
    AGENT_LABEL: "Primary Agent",
    STATUS_LABEL: "Status",
    DISPATCHED_LABEL: "Dispatched at",
    TITLE_WITH_ID: (id: string) => `Execution / ${id}`,
    STATS_FORMAT: (status: string, latencyMs: number) => `${status} · ${latencyMs}ms`,
    STEPS_VALUE: (completed: number, total: number) => `${completed}/${total}`,
    LATENCY_VALUE: (latencyMs: number) => `${latencyMs}ms`,
  },
  WATERFALL: {
    TITLE: "Distributed Tracing (OpenTelemetry)",
    EMPTY_DESC: "No OpenTelemetry spans recorded for this execution session yet.",
    SPANS_LABEL: "Execution Spans",
    TOTAL_LABEL: (ms: number) => `Total: ${ms}ms`,
    TOTAL_DURATION: (ms: number) => `Total: ${ms}ms`,
    SPAN_ID: (id: string) => `Span ID: ${id}`,
    NO_ATTRIBUTES: "No span attributes",
  },
  REPLAYER: {
    TITLE: "Checkpoint Time-Travel Replayer",
    TOAST_FORK: (index: number, label: string) =>
      `Replaying execution from checkpoint #${index}: "${label}"`,
    PLAY: "Play",
    PAUSE: "Pause",
    FORK_HERE: "Fork Here",
    STEP_LABEL: (current: number, total: number) => `Checkpoint ${current} of ${total}`,
    A11Y_PREV: "Previous checkpoint",
    A11Y_NEXT: "Next checkpoint",
    A11Y_SLIDER: "Checkpoint scrubber slider",
  },
  DAG: {
    TITLE: "Execution DAG Graph",
    SUBTITLE: (nodes: number, zoomPct: number) => `(${nodes} nodes · zoom ${zoomPct}%)`,
    ZOOM_IN_A11Y: "Zoom in DAG graph",
    ZOOM_OUT_A11Y: "Zoom out DAG graph",
    RESET_ZOOM_A11Y: "Reset DAG graph zoom",
    STEP_LABEL: (index: number) => `Step ${index}`,
    MS_FORMAT: (ms: number) => `${ms}ms`,
    TOK_FORMAT: (tokens: number) => `${tokens} tok`,
    NODE_DETAILS: "Node Details:",
    STATUS_LABEL: "Status:",
    STEP_INDEX: "Step Index",
    LATENCY: "Latency",
    TOKENS_USED: "Tokens Used",
    ERROR: "Error",
    NONE: "None",
  },
  DEBUG_DIALOG: {
    TITLE: "Execution Debug Trace",
    DESCRIPTION: (id: string) =>
      `Forensic developer debug details, execution metrics, and DAG trace for execution ${id}.`,
    FAILURE_TITLE: "Execution Failure",
    ID_PREFIX: (id: string) => `ID: ${id}`,
    COPY_ID_TOOLTIP: "Copy Execution ID",
    OPEN_SESSION: "Open Session Thread",
    SPECIALIST_LABEL: "Specialist",
    MODEL_ENGINE_LABEL: "Model Engine",
    MODE_LABEL: (mode: string) => `${mode} mode`,
    DURATION_LATENCY_LABEL: "Duration & Latency",
    MS_TOTAL: (ms: number) => `${ms.toLocaleString()}ms total`,
    PROGRESS_TOKENS_LABEL: "Progress & Tokens",
    STEP_PROGRESS: (completed: number, total: number) => `Step ${completed}/${total}`,
    TOKENS_FORMAT: (tokens: number) =>
      tokens > 0 ? `${tokens.toLocaleString()} tokens` : "0 tokens",
    DAG_CHECKPOINTS: "DAG Step Checkpoints",
    JSON_PAYLOAD_TITLE: "Forensic JSON Payload",
    COPY_JSON: "Copy JSON",
  },
  TABLE: {
    COPY_ID_TOOLTIP: "Copy full Execution ID",
    DEBUG_TOOLTIP: "Open developer debug trace",
    DEBUG_BTN: "Debug",
    SESSION_TOOLTIP: "Open live session thread",
    SESSION_BTN: "Session",
  },
} as const;
