/**
 * @file apps/console/src/lib/ui-copy/models.ts
 * @description Centralized UI copy, placeholders, and dialog text for LLM Models & Providers.
 * @module apps/console/lib/ui-copy
 */

export const MODELS_COPY = {
  PAGE_TITLE: "Models & Providers",
  BREADCRUMB: "Models",
  PAGE_DESCRIPTION: "Local and cloud inference providers configured in this cluster.",
  REGISTER_BUTTON: "Add Model",
  STATS: (count: number) => `${count} models configured`,
  EMPTY_TITLE: "No Inference Models Configured",
  EMPTY_DESC: "Connect Ollama, OpenAI, or Anthropic providers to power autonomous agents.",
  TAB_CATALOG: "Model Catalog",
  TAB_COCKPIT: "Cost & Latency Cockpit",
  COCKPIT: {
    CLUSTER_P95_TITLE: "Cluster P95 Latency",
    CLUSTER_P95_ROUTING: "Dynamic Lowest-Latency Routing Active",
    TOKEN_SPEND_TITLE: "Current Month Token Spend",
    TOKEN_SPEND_CAP: (spendPct: number, cap: number) => `${spendPct}% of $${cap} cap`,
    QUOTA_STATUS_TITLE: "Quota Enforcement Status",
    QUOTA_STATUS_NORMAL: "NORMAL",
    QUOTA_WARNING: (pct: number) => `Threshold warning at ${pct}%`,
    FALLBACK_CASCADE_TITLE: "Fallback Cascade",
    FALLBACK_CASCADE_TIERS: (count: number) => `${count} Tiers`,
    FALLBACK_CASCADE_PATH: "Google → Anthropic → OpenAI",
    TABLE_TITLE: "Provider Latency & Rate Matrix",
    STRATEGIES: {
      LOWEST_LATENCY: "Lowest Latency",
      LEAST_EXPENSIVE: "Least Expensive",
      ROUND_ROBIN: "Round Robin",
    } as Record<string, string>,
    HEADERS: {
      ENGINE: "Provider Engine",
      P50: "P50",
      P95: "P95",
      P99: "P99",
      PROMPT_1K: "Prompt / 1k",
      COMPL_1K: "Compl / 1k",
      AVAILABILITY: "Availability",
    },
    LATENCY_MS: (ms: number) => `${ms}ms`,
    PERCENTAGE: (pct: number) => `${pct}%`,
    COST_FORMAT: (cost: number) => `$${cost.toFixed(4)}`,
  },
  DIALOG: {
    TITLE: "Add LLM Model",
    DESCRIPTION: "Register a new AI model under an active provider.",
    SUBMIT_BUTTON: "Add Model",
    PROVIDER_LABEL: "Provider",
    NAME_LABEL: "Display Name",
    NAME_PLACEHOLDER: "e.g. Primary Model",
    IDENTIFIER_LABEL: "Model Identifier",
    IDENTIFIER_PLACEHOLDER: "e.g. model-identifier-tag",
    CONTEXT_WINDOW_LABEL: "Context Window (tokens)",
    CONTEXT_WINDOW_PLACEHOLDER: "32768",
    DEFAULT_ENGINE_LABEL: "Default Engine",
    STANDARD_MODEL_LABEL: "Standard Catalog Model",
    DEFAULT_MODEL_LABEL: "Default AI Engine",
    DESC_LABEL: "Description",
    DESC_PLACEHOLDER: "Model capabilities and notes...",
    FALLBACK_NAME: "Custom Model",
    FALLBACK_IDENTIFIER: "custom-model",
    TOAST_LOADING: "Registering model...",
    TOAST_SUCCESS: "Model registered successfully!",
    TOAST_ERROR: "Failed to register model",
  },

  CARD: {
    DEFAULT_BADGE: "Default",
    DELETE_TOOLTIP: "Remove model from cluster",
    CONTEXT_WINDOW: (tokens: number) => `${(tokens / 1024).toFixed(0)}k context`,
    FALLBACK_PROVIDER: "LLM Engine",
    STATUS_OPERATIONAL: "Operational",
    STATUS_OFFLINE: "Offline",
    LATENCY_LABEL: "Latency",
    CONTEXT_LABEL: "Context",
    COST_LABEL: "Cost",
    KEY_CONNECTED: "API key connected",
    NO_KEY: "No key configured",
    MS_FORMAT: (ms: number) => `${ms}ms`,
  },
} as const;
