/**
 * @file packages/rag/src/embeddings/embedding-provider.interface.ts
 * @description Contract for text embedding providers in RAG vector processing.
 */

/**
 * Common contract for embedding providers transforming text into vector representations.
 */
export interface IEmbeddingProvider {
  /**
   * Dimensionality of vectors generated by this provider (e.g. 1536, 768, 384).
   */
  readonly dimension: number;

  /**
   * Generates a dense normalized vector embedding for a single text string.
   *
   * @param text - Plain text input
   * @returns Array of floating-point numbers representing the vector
   */
  embedText(text: string): Promise<number[]>;

  /**
   * Generates dense vector embeddings for a batch of text strings.
   *
   * @param texts - Array of plain text inputs
   * @returns Array of vector embeddings corresponding to each input text
   */
  embedBatch(texts: string[]): Promise<number[][]>;
}
